-- GradSync: Clear All Student Data
-- Run this to delete all data from the database

USE DATABASE GRADSYNC_DB;
USE WAREHOUSE GRADSYNC_WH;

-- Delete data in correct order (child tables first, then parent)
DELETE FROM APP.TEACHER_NOTES WHERE 1=1;
DELETE FROM APP.AI_INSIGHTS WHERE 1=1;
DELETE FROM APP.INTERVENTION_LOG WHERE 1=1;
DELETE FROM RAW_DATA.GRADES WHERE 1=1;
DELETE FROM RAW_DATA.ATTENDANCE WHERE 1=1;
DELETE FROM RAW_DATA.BULK_UPLOAD_STAGING WHERE 1=1;
DELETE FROM RAW_DATA.STUDENTS WHERE 1=1;

-- Verify all tables are empty
SELECT 'Students' as table_name, COUNT(*) as row_count FROM RAW_DATA.STUDENTS
UNION ALL
SELECT 'Attendance', COUNT(*) FROM RAW_DATA.ATTENDANCE
UNION ALL
SELECT 'Grades', COUNT(*) FROM RAW_DATA.GRADES
UNION ALL
SELECT 'Teacher Notes', COUNT(*) FROM APP.TEACHER_NOTES;
